name: Supabase Database Query

on:
  schedule:
    - cron: '0 0 */5 * *'  # Runs every 5 days at midnight UTC

jobs:
  query-database:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @supabase/supabase-js
        
      - name: Run database query
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          node -e '
            const { createClient } = require("@supabase/supabase-js");
            
            const supabaseUrl = process.env.SUPABASE_URL;
            const supabaseKey = process.env.SUPABASE_ANON_KEY;
            
            const supabase = createClient(supabaseUrl, supabaseKey);
            
            async function runQuery() {
              try {
                // Replace this query with your actual query
                const { data, error } = await supabase
                  .from("documents")
                  .select("*")
                  .limit(10);
                
                if (error) throw error;
                
                console.log("Query results:", data);
              } catch (error) {
                console.error("Error running query:", error.message);
                process.exit(1);
              }
            }
            
            runQuery();
          ' 